module.exports = {
    "zh-cn": {
        "Schedule": "日程",
        "All": "全部",
        "NoneData": "暂无日程",
        "ErrorLoadData": "加载失败",
        "Date_ALLDay":"全天",
        "Date_Begin":"开始于",
 	    "Date_End":"结束于",
        'Mon': '一',
        'Tues': '二',
        'Wed': '三',
        'Thurs': '四',
        'Fri': '五',
        'Sat': '六',
        'Sun': '日',
        'AllSchedule':'共%s个日程'
    },
    "zh-hk": {
        "Schedule": "日程",
        "All": "全部",
        "NoneData": "暫無日程",
        "ErrorLoadData": "加載失敗",
        "Date_ALLDay":"全天",
        "Date_Begin":"開始于",
 	    "Date_End":"結束于",
        'Mon': '壹',
        'Tues': '二',
        'Wed': '三',
        'Thurs': '四',
        'Fri': '五',
        'Sat': '六',
        'Sun': '日',
        'AllSchedule':'共%s個日程'
    },
    "en": {
        "Schedule": "Schedule",
        "All": "All",
        "Date_ALLDay":"All day",
        "Date_Begin":"start with",
        "Date_End":"end with",
        "NoneData": "No schedule",
        "ErrorLoadData": "loading failed",
        'Mon': 'Mon',
        'Tues': 'Tue',
        'Wed': 'Wed',
        'Thurs': 'Thu',
        'Fri': 'Fri',
        'Sat': 'Sat',
        'Sun': 'Sun',
        'AllSchedule':'A total of %s Schedule'
    }
}